### ISSUE TITLE
UIResponder not recognized

### ISSUE THREAD

**Issue by oscarjiv91** [elliottsj/apple-watch-uikit#1]
I have tried to run the example and create a new project following the steps. When I run `./build.sh` everything goes well, but in the `main.m` I get the error: `cannot find interface for class UIResponder`.

**Comment by elliottsj** [comment]
Which step causes that error? Does it show up in Xcode or just in the build.sh output? Also which version of OS X and Xcode are you using?

**Comment by oscarjiv91** [comment]
The `build.sh` runs well. It shows in xcode. Also when I run the app without rebuilding (after running build.sh) it says 'There is nothing built for scheme "AppleWatchUIKit"', so I have to click in 'Build and Run'. Maybe that is the problem?

I'm using OS X El Capitan 10.11.5. and Xcode 7.3.1

<img width="1137" alt="captura de pantalla 2016-07-06 a las 10 28 34 a m" src="https://cloud.githubusercontent.com/assets/4256218/16621492/6ef4524c-4364-11e6-9811-d569559d410d.png">

**Comment by elliottsj** [comment]
Hmm, I think I've seen this before, but I don't recall how I resolved it 😕 

When you build, make sure you select the "WatchKit App" target and build for an actual device (if you have one):
![screenshot 2016-07-06 11 06 35](https://cloud.githubusercontent.com/assets/2177366/16622927/e252680a-4369-11e6-9354-033160bbb68b.png)

If you're using the simulator, you may need to patch `/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/` instead of `/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/`, but I haven't tried that yet.

**Comment by oscarjiv91** [comment]
I'm using the simulator. Will try that. Thanks!
